INSERT INTO public.questions_attractive ("id","name","type") VALUES 
(10,'Link do vídeo','criação')
,(11,'Análise do setor','criação')
,(12,'Análise de mercado','criação')
,(13,'Análise de concorrentes','criação')
,(14,'Inovação de valor','criação')
,(15,'Descrição do problema','criação')
,(16,'Descrição da solução','criação')
,(17,'Descrição da vantagem competitiva','criação')
,(18,'Qual é o problema?','tração')
,(19,'Quais evidências sustentam que o problema existe?','tração')
;
INSERT INTO public.questions_attractive ("id","name","type") VALUES 
(20,'O problema é urgente, mal atendido, impraticável e/ou inevitável?','tração')
,(21,'O problema é visível e/ou crítico?','tração')
,(22,'Quem é o cliente-alvo?','tração')
,(23,'Quais são as necessidades e desejos deles?','tração')
,(24,'Qual é o tamanho do mercado?','tração')
,(25,'Quais ganhos os clientes experimentarão?','tração')
,(26,'Que dores os clientes experimentarão?','tração')
,(27,'Quem são os concorrentes e seus clientes?','tração')
,(28,'Quais são os seus recursos mínimos viáveis?','tração')
,(29,'Por que esses recursos são valiosos e raros?','tração')
;
INSERT INTO public.questions_attractive ("id","name","type") VALUES 
(30,'Qual é o seu protótipo?','tração')
,(31,'Quais são as estratégias e preços dos concorrentes?','tração')
,(32,'Qual é a nossa estratégia e preços?','tração')
,(33,'Quais são seus canais de distribuição?','tração')
,(34,'Quem são seus intermediários?','tração')
,(35,'Qual é o plano e o orçamento de publicidade?','tração')
,(36,'Qual é o plano de relações públicas?','tração')
,(37,'Qual é o plano de vendas pessoais?','tração')
,(38,'Qual é o plano e o orçamento de marketing direto?','tração')
,(39,'Qual é o plano e orçamento de promoção de vendas?','tração')
;
INSERT INTO public.questions_attractive ("id","name","type") VALUES 
(40,'Quais tipos de fluxos de receita são usados pelos concorrentes?','tração')
,(41,'Que tipos de fluxos de receita usará?','tração')
,(42,'Quais são suas receitas estimadas no primeiro e no segundo ano?','tração')
,(43,'Quais são seus custos estimados detalhados no primeiro e no segundo ano?','tração')
,(44,'Qual é o seu processo de venda?','tração')
,(45,'Quais são suas necessidades de financiamento?','tração')
,(46,'Quem são suas fontes candidatas de financiamento?','tração')
,(47,'Quem são os fundadores?','tração')
,(48,'Quem são os mentores?','tração')
,(49,'Quem são os principais parceiros?','tração')
;